# Generated by Django 5.1.4 on 2025-01-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofile', '0002_photohub_delete_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photohub',
            name='time',
        ),
        migrations.AddField(
            model_name='photohub',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photohub',
            name='images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
