# Generated by Django 5.1.4 on 2025-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofile', '0004_authentic_photohub_user_alter_photohub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentic',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
